# Site settings
title: EVERTims Website
email: evertims@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 EVERTims is a framework for real-time auralization in Virtual Reality

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# twitter_username: volnyio
github_username:  EVERTims

# Build settings
markdown: kramdown
